using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using BlazeJump.Tools.Enums;
using Newtonsoft.Json;

namespace BlazeJump.Tools.Models.NostrConnect;

/// <summary>
/// Represents an active Nostr Connect session between a web client and an application.
/// </summary>
public class NostrConnectSession
{
    /// <summary>
    /// Initializes a new instance of the <see cref="NostrConnectSession"/> class.
    /// </summary>
    /// <param name="ourPubkey">The ephemeral public key generated by the web client for this session.</param>
    // Parameterless constructor for persistence
    public NostrConnectSession() { }

    public NostrConnectSession(string ourPubkey)
    {
        SessionId = Guid.NewGuid().ToString();
        OurPubkey = ourPubkey;
    }

    /// <summary>
    /// Gets or sets the unique session identifier. Defaults to a new GUID.
    /// </summary>
    /// <summary>
    /// Gets or sets the unique session identifier. Defaults to a new GUID.
    /// </summary>
    public string SessionId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the user's public key (foreign key to UserProfile).
    /// </summary>
    public string OurPubkey { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the ephemeral public key generated by the web client for this session.
    /// </summary>
    public string TheirPubkey { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the relay URLs used for this session.
    /// </summary>
    public List<string>? Relays { get; set; }

    /// <summary>
    /// Gets or sets the secret used for this session connection.
    /// </summary>
    public string? Secret { get; set; }

    /// <summary>
    /// Gets or sets the permissions granted for this session.
    /// </summary>
    public List<string> Permissions { get; set; } = new();

    private SessionStatusEnum _previousStatus = SessionStatusEnum.Idle;

    /// <summary>
    /// Event raised when the session status changes.
    /// </summary>
    public event EventHandler<SessionStatusEnum>? StatusChanged;

    /// <summary>
    /// Gets the current status based on which fields are populated.
    /// SYN: Only OurPubkey is set
    /// SYNACK: TheirPubkey is also set
    /// Connected: ConnectedAt timestamp is set
    /// Disconnected: Explicitly marked as disconnected
    /// </summary>
    public SessionStatusEnum Status
    {
        get
        {
            var currentStatus = CalculateStatus();
            
            if (currentStatus != _previousStatus)
            {
                _previousStatus = currentStatus;
                StatusChanged?.Invoke(this, currentStatus);
            }
            
            return currentStatus;
        }
    }

    /// <summary>
    /// Gets or sets the UTC timestamp when the session was successfully connected. Null if not yet connected.
    /// </summary>
    public DateTime? ConnectedAt { get; set; }

    /// <summary>
    /// Gets or sets the UTC timestamp when the session was successfully connected. Null if not yet connected.
    /// </summary>
    public DateTime? LastActive { get; set; }

    private SessionStatusEnum CalculateStatus()
    {
        if (string.IsNullOrEmpty(TheirPubkey))
        {
            return SessionStatusEnum.AwaitingScan; // SYN
        }
        
        if (!string.IsNullOrEmpty(TheirPubkey) && !ConnectedAt.HasValue)
        {
            return SessionStatusEnum.ResponseSent; // SYNACK
        }
        
        if (ConnectedAt.HasValue)
        {
            return SessionStatusEnum.Connected;
        }
        
        return SessionStatusEnum.Idle;
    }

    /// <summary>
    /// Gets whether the session is fully connected.
    /// </summary>
    public bool IsConnected => Status == SessionStatusEnum.Connected;

    /// <summary>
    /// Sets the user's public key. Single use only.
    /// </summary>
    public void SetTheirPubkey(string theirPubkey)
    {
        if(string.IsNullOrEmpty(TheirPubkey))
            TheirPubkey = theirPubkey;
    }

    /// <summary>
    /// Marks the session as fully connected.
    /// </summary>
    public void SetConnected()
    {
        ConnectedAt = DateTime.UtcNow;
        LastActive = DateTime.UtcNow;
    }

    /// <summary>
    /// Updates activity timestamp - call on any successful message exchange.
    /// </summary>
    public void UpdateActivity()
    {
        LastActive = DateTime.UtcNow;
    }
}